import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const pdfService = {
  /**
   * Generate Policy PDF
   */
  generatePolicyPDF(policy: any, customer: any) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('SMARTINSURANCE', pageWidth / 2, 20, { align: 'center' });
    doc.setFontSize(12);
    doc.text('Policy Document', pageWidth / 2, 30, { align: 'center' });

    // Policy details
    doc.setTextColor(0, 0, 0);
    let y = 55;

    // Policy Number
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Policy Number:', 20, y);
    doc.setFont('helvetica', 'bold');
    doc.text(policy.policyNumber, 70, y);
    y += 10;

    // Status
    doc.setFont('helvetica', 'normal');
    doc.text('Status:', 20, y);
    doc.setFont('helvetica', 'bold');
    const statusColor = policy.status === 'ACTIVE' ? [16, 185, 129] : policy.status === 'PENDING' ? [245, 158, 11] : [107, 114, 128];
    doc.setTextColor(...statusColor);
    doc.text(policy.status, 70, y);
    doc.setTextColor(0, 0, 0);
    y += 15;

    // Customer Details Section
    doc.setFillColor(243, 244, 246);
    doc.rect(15, y - 5, pageWidth - 30, 10, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('CUSTOMER DETAILS', 20, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${customer?.firstName || ''} ${customer?.lastName || ''}`, 20, y);
    y += 7;
    doc.text(`Email: ${customer?.email || 'N/A'}`, 20, y);
    y += 7;
    if (customer?.phone) {
      doc.text(`Phone: ${customer.phone}`, 20, y);
      y += 7;
    }
    y += 10;

    // Policy Details Section
    doc.setFillColor(243, 244, 246);
    doc.rect(15, y - 5, pageWidth - 30, 10, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('POLICY DETAILS', 20, y);
    y += 10;

    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
      }).format(amount);
    };

    const formatDate = (date: string) => {
      return new Date(date).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'long',
        year: 'numeric',
      });
    };

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const policyDetails = [
      ['Policy Type', policy.policyType],
      ['Sum Assured', formatCurrency(parseFloat(policy.sumAssured))],
      ['Premium Amount', formatCurrency(parseFloat(policy.premiumAmount))],
      ['Premium Frequency', policy.premiumFrequency],
      ['Start Date', formatDate(policy.startDate)],
      ['End Date', formatDate(policy.endDate)],
      ['Tenure', `${policy.tenureYears} Years`],
    ];

    autoTable(doc, {
      startY: y,
      head: [],
      body: policyDetails,
      theme: 'plain',
      styles: { fontSize: 10, cellPadding: 3 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 'auto' },
      },
      margin: { left: 20 },
      tableWidth: 'wrap',
    });

    // Description if exists
    if (policy.description) {
      const finalY = (doc as any).lastAutoTable.finalY + 10;
      doc.setFont('helvetica', 'bold');
      doc.text('Description:', 20, finalY);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(policy.description, pageWidth - 40);
      doc.text(lines, 20, finalY + 7);
    }

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by SmartInsurance', pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, pageHeight - 5, { align: 'center' });

    return doc;
  },

  /**
   * Generate Claim PDF
   */
  generateClaimPDF(claim: any, policy: any) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(239, 68, 68);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('SMARTINSURANCE', pageWidth / 2, 20, { align: 'center' });
    doc.setFontSize(12);
    doc.text('Claim Receipt', pageWidth / 2, 30, { align: 'center' });

    // Claim details
    doc.setTextColor(0, 0, 0);
    let y = 55;

    // Claim Number
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Claim Number:', 20, y);
    doc.setFont('helvetica', 'bold');
    doc.text(claim.claimNumber, 70, y);
    y += 10;

    // Status
    doc.setFont('helvetica', 'normal');
    doc.text('Status:', 20, y);
    doc.setFont('helvetica', 'bold');
    const statusColors: Record<string, number[]> = {
      SUBMITTED: [59, 130, 246],
      UNDER_REVIEW: [245, 158, 11],
      APPROVED: [16, 185, 129],
      REJECTED: [239, 68, 68],
      CLOSED: [107, 114, 128],
    };
    doc.setTextColor(...(statusColors[claim.status] || [0, 0, 0]));
    doc.text(claim.status.replace('_', ' '), 70, y);
    doc.setTextColor(0, 0, 0);
    y += 15;

    // Claim Details Section
    doc.setFillColor(243, 244, 246);
    doc.rect(15, y - 5, pageWidth - 30, 10, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('CLAIM DETAILS', 20, y);
    y += 10;

    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
      }).format(amount);
    };

    const formatDate = (date: string) => {
      if (!date) return 'N/A';
      return new Date(date).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'long',
        year: 'numeric',
      });
    };

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const claimDetails = [
      ['Claim Type', claim.claimType],
      ['Claim Amount', formatCurrency(parseFloat(claim.claimAmount))],
      ['Claim Reason', claim.claimReason],
      ['Incident Date', formatDate(claim.incidentDate)],
      ['Submitted Date', formatDate(claim.submittedAt)],
    ];

    if (claim.approvedAmount) {
      claimDetails.push(['Approved Amount', formatCurrency(parseFloat(claim.approvedAmount))]);
    }
    if (claim.reviewNotes) {
      claimDetails.push(['Review Notes', claim.reviewNotes]);
    }

    autoTable(doc, {
      startY: y,
      head: [],
      body: claimDetails,
      theme: 'plain',
      styles: { fontSize: 10, cellPadding: 3 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 'auto' },
      },
      margin: { left: 20 },
      tableWidth: 'wrap',
    });

    // Policy details
    if (policy) {
      const finalY = (doc as any).lastAutoTable.finalY + 10;
      doc.setFillColor(243, 244, 246);
      doc.rect(15, finalY - 5, pageWidth - 30, 10, 'F');
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('RELATED POLICY', 20, finalY);

      const policyInfo = [
        ['Policy Number', policy.policyNumber],
        ['Policy Type', policy.policyType],
      ];

      autoTable(doc, {
        startY: finalY + 5,
        head: [],
        body: policyInfo,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 50 },
          1: { cellWidth: 'auto' },
        },
        margin: { left: 20 },
        tableWidth: 'wrap',
      });
    }

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by SmartInsurance', pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, pageHeight - 5, { align: 'center' });

    return doc;
  },

  /**
   * Generate Premium Receipt PDF
   */
  generateReceiptPDF(payment: any, policy: any) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(16, 185, 129);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('SMARTINSURANCE', pageWidth / 2, 20, { align: 'center' });
    doc.setFontSize(12);
    doc.text('Payment Receipt', pageWidth / 2, 30, { align: 'center' });

    // Receipt details
    doc.setTextColor(0, 0, 0);
    let y = 55;

    // Receipt Number
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Receipt Number:', 20, y);
    doc.setFont('helvetica', 'bold');
    doc.text(payment.receiptNumber, 70, y);
    y += 10;

    // Status
    doc.setFont('helvetica', 'normal');
    doc.text('Status:', 20, y);
    doc.setFont('helvetica', 'bold');
    const statusColor = payment.status === 'PAID' ? [16, 185, 129] : payment.status === 'PENDING' ? [245, 158, 11] : [239, 68, 68];
    doc.setTextColor(...statusColor);
    doc.text(payment.status, 70, y);
    doc.setTextColor(0, 0, 0);
    y += 15;

    // Payment Details Section
    doc.setFillColor(243, 244, 246);
    doc.rect(15, y - 5, pageWidth - 30, 10, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('PAYMENT DETAILS', 20, y);
    y += 10;

    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
      }).format(amount);
    };

    const formatDate = (date: string) => {
      return new Date(date).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'long',
        year: 'numeric',
      });
    };

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const paymentDetails = [
      ['Amount', formatCurrency(parseFloat(payment.amount))],
      ['Payment Date', formatDate(payment.paymentDate)],
      ['Due Date', formatDate(payment.dueDate)],
      ['Payment Method', payment.paymentMethod],
    ];

    if (payment.transactionRef) {
      paymentDetails.push(['Transaction Ref', payment.transactionRef]);
    }
    if (payment.remarks) {
      paymentDetails.push(['Remarks', payment.remarks]);
    }

    autoTable(doc, {
      startY: y,
      head: [],
      body: paymentDetails,
      theme: 'plain',
      styles: { fontSize: 10, cellPadding: 3 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 'auto' },
      },
      margin: { left: 20 },
      tableWidth: 'wrap',
    });

    // Policy details
    if (policy) {
      const finalY = (doc as any).lastAutoTable.finalY + 10;
      doc.setFillColor(243, 244, 246);
      doc.rect(15, finalY - 5, pageWidth - 30, 10, 'F');
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('RELATED POLICY', 20, finalY);

      const policyInfo = [
        ['Policy Number', policy.policyNumber],
        ['Policy Type', policy.policyType],
      ];

      autoTable(doc, {
        startY: finalY + 5,
        head: [],
        body: policyInfo,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 50 },
          1: { cellWidth: 'auto' },
        },
        margin: { left: 20 },
        tableWidth: 'wrap',
      });
    }

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by SmartInsurance', pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, pageHeight - 5, { align: 'center' });

    return doc;
  },

  /**
   * Download PDF
   */
  downloadPDF(doc: jsPDF, filename: string) {
    doc.save(`${filename}.pdf`);
  },

  /**
   * Open PDF in new tab
   */
  openPDF(doc: jsPDF) {
    const blob = doc.output('blob');
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
  },
};
